#ifndef RESTGATE_CONFIG_H
#define RESTGATE_CONFIG_H

#include <QtCore/qglobal.h>

#define RESTGATE_VERSION_MAJOR 1
#define RESTGATE_VERSION_MINOR 0
#define RESTGATE_VERSION_PATCH 1
#define RESTGATE_VERSION_STR   "1.0.1"
#define RESTGATE_VERSION       RESTGATE_VERSION_CHECK(RESTGATE_VERSION_MAJOR, RESTGATE_VERSION_MINOR, RESTGATE_VERSION_PATCH)
#define RESTGATE_VERSION_CHECK QT_VERSION_CHECK

#endif // RESTGATE_CONFIG_H
